server:
  port: 8080

spring:
  application:
    name: authodo-service

  config:
    import: optional:file:.env.${spring.profiles.active}[.properties]

  messages:
    basename: messages
    encoding: UTF-8

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=${SERVER_TIME_ZONE}&characterEncoding=${CHARACTER_ENCODING}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
    open-in-view: false

logging:
  level:
    root: info
    com.zaxxer: debug
    org.springframework.security.web: trace
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

jwt:
  secret: ${JWT_SECRET}
  access:
    expiration-ms: ${JWT_ACCESS_EXPIRATION_MS}
  refresh:
    expiration-ms: ${JWT_REFRESH_EXPIRATION_MS}

springdoc:
  swagger-ui:
    url: /docs/openapi3.yaml
    operationsSorter: alpha
    tagsSorter: alpha
